### ISSUE TITLE
Giving parameters when calling an agent fails

### ISSUE THREAD

**Issue by DavoudTaghawiNejad** [AB-CE/abce#114]
agent.do_something(param=5), works
but agent.do_something(5) does not.

I don't know how to resolve this.

**Comment by rht** [comment]
@DavoudTaghawiNejad why is the ticket closed? Sounds reasonable that agent action should take non-keyword parameters.

**Comment by DavoudTaghawiNejad** [comment]
Its closed as my next pull request will solve this problem.
