### ISSUE TITLE
Persistence/serialization: reduce to using one data format

### ISSUE THREAD

**Issue by rht** [AB-CE/abce#16]
Currently, the complete logging data is stored as a combination of sqlite file (slow because of synchronous write to fs) + csv files for panel and aggregate. It'd be simpler to use just one format (one file) that can be readily ported to / parsed by other platforms.

The fastest out there is ujson[1] though with this, it is not possible to append/modify an entry without having to load the entire file into the memory.

[1] https://blog.hartleybrody.com/python-serialize/

**Comment by DavoudTaghawiNejad** [comment]
Good idea as long as at the end there is a file that is easily importable
to R and excel.

**Comment by rht** [comment]
Well, R reads json just fine (and other ABM frameworks are definitely so). Such key-value json file can be easily converted to xls as necessary.

Note that, after quick measurement, I discovered logging takes about 16% of the simulation time.

**Comment by rht** [comment]
So, the default serialization format should be json, and implement postprocessing to_xls()?

**Comment by DavoudTaghawiNejad** [comment]
An additional constraint is it must all be pypy3 compatible.

**Comment by DavoudTaghawiNejad** [comment]
I think this is resolved. Sqlite is not syncronized, but its all unified and simplified

**Comment by DavoudTaghawiNejad** [comment]
Actually, basic layout could be rewritten in such a way that it gets the sqlite database from memory and does not read the csv files. Then generating csv file could be made optional.
