### ISSUE TITLE
abce firms 50000 example

### ISSUE THREAD

**Issue by Sirorezka** [AB-CE/abce#169]
File 50000_firms/b.py contains classes that no longer exist

50000_firms/youragent.py error in:
` assert self['cookie'] == 0`
should be:
`assert self.not_reserved('cookie') ==0`

**Comment by rht** [comment]
Fixed in latest master as of https://github.com/AB-CE/examples/commit/720c673ce53e3e80d6d493485baaafd3941d0dce.
