### ISSUE TITLE
is there link agent like the one in Netlogo?

### ISSUE THREAD

**Issue by Westlife1002** [AB-CE/abce#183]
I used Netlogo a lot and I found it is not constraining anything I want to build. However, I am interested to learn Python based ABS. One of the key question is if there is a agent type as link (directed or undirected) and supports the related primitive commands (methods)? (see https://ccl.northwestern.edu/netlogo/docs/dictionary.html#linkgroup)

**Comment by rht** [comment]
@Westlife1002 I suppose you could manually make an agent with `link_from`, and `link_to` attributes.
```python
class LinkedAgent:
    def __init__(self, *args, **kwargs):
        self.link_from = []
        self.link_to = []
    def link_to(self, target):
        self.link_to.append(target)
        target.link_from.append(self)
```

**Comment by rht** [comment]
Marked as resolved. Let me know if it is otherwise.
