### ISSUE TITLE
simulation.graphs()

### ISSUE THREAD

**Issue by zhangc927** [AB-CE/abce#184]
simulation.graphs()   happend **"NameError: name 'form' is not defined**",If you understand, please teach me.
thank you!
![1552526327(1)](https://user-images.githubusercontent.com/33982420/54324867-723a9480-463a-11e9-855b-0fd73ccf1a08.png)

**Comment by DavoudTaghawiNejad** [comment]
This is a bug from a dependency library. It requires an update. I will provide the update soon.

**Comment by zhangc927** [comment]
thank you very much @DavoudTaghawiNejad

**Comment by rht** [comment]
#208 will remove the GUI code, so that `simulation.graphs()` is now obsolete. If anyone wants to do GUI they can do it via the mature Jupyter widgets.

**Comment by rht** [comment]
https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Basics.html
