### ISSUE TITLE
Walk Trough doc page is not correct/outdated?

### ISSUE THREAD

**Issue by ipcoder** [AB-CE/abce#189]
Functions mentioned in https://abce.readthedocs.io/en/master/Walk_through.html are not found in the `Simulation` class, like 

```python
simulation.declare_round_endowment(resource='labor_endowment', units=1, product='labor')
simulation.declare_perishable(good='labor')
```

as well as also mentioned below in the text `abcEconomics.Simulation.declare_service()` and `abcEconomics.Simulation.declare_round_endowment()`

That leads to errors running examples, like CCE.

Can you clarify from the design point of view, does that mean principal changes in dealing with resources?
Thanks

**Comment by rht** [comment]
Yeah the walkthrough is outdated.
