### ISSUE TITLE
[gui] Offload gui handling to jupyter

### ISSUE THREAD

**Issue by rht** [AB-CE/abce#19]
Advantages:
- Less maintenance overhead. There are plenty features/engines that need to be implemented yet.
- More standardized format. Most comp sci 'lab books' are stored in .ipynb.

!Advantages:
- Less freedom in implementing temporal events because jupyter notebooks are declarative.

**Comment by DavoudTaghawiNejad** [comment]
It works on jupyter, see here: http://abce.readthedocs.io/en/0.9b/jupyter_tutorial.html. 

GUI is needed for my future research in Brazil.
