### ISSUE TITLE
Individual trade log throws an exception

### ISSUE THREAD

**Issue by DoofCoder** [AB-CE/abce#195]
Hi, I enabled trade logging in the call of simulation as:
`sim = abce.Simulation(name="Market model", trade_logging='individual', processes=1)`

and when run, I got the exception: 

...\abce\abcEconomics\trade.py in _log_receive_accept_agent(self, offer)
    690         else:
    691             self._trade_log[(offer.good, '%s_%i' % (
--> 692                 offer.receiver[0], offer.receiver[1]), self.name_without_colon, offer.price)] += offer.quantity
    693 
    694     def _receive_reject(self, offer_id):

AttributeError: 'Buyer' object has no attribute 'name_without_colon'

**Comment by rht** [comment]
The name_without_colon attribute is probably obsolete. I will see if it can be removed.

**Comment by DoofCoder** [comment]
Yep. In fact I solved it in my fork by creating a new member variable name_without_colon in the Agent class and defined it like: 
`self.name_without_colon = f'{group}_{id}'`

**Comment by rht** [comment]
From git archaeology, I found that at about 200 commits prior to the current master `self.name_without_colon` is initialized at `Agent`'s `__init__` as

```self.name_without_colon = '%s_%i' % (group, id)```, just like your patch. Since an agent needs to have a string representation of its name, this `name_without_colon` should probably be added back.

**Comment by DoofCoder** [comment]
Thnx. By the way I'm evaluating using ABCE for modelling a power system market model. So I am extensibly undertanding the ABCE code. I can help with a slow-burn level of support to maintain some of it. It provide quite good funtionality but lacks a little support.

Let me know if I can be of help.

**Comment by rht** [comment]
Our current goal is in simplifying the library to make it more readable and simpler, and to make code structure at the ABM layer to be compatible with Mesa's API.
Any contribution to simplify the library are welcome!

**Comment by DoofCoder** [comment]
Ok great. And the integration with Mesa is a great goal. We need powerful ABM tools in Python. I'll have that in mind and hope to be useful.
I don't know the mechanics for contributing though.

**Comment by rht** [comment]
@DoofCoder you could read the source and add comments/annotation to the parts that are undocumented and make a pull request for these, or make a new example for https://github.com/ab-ce/examples.
