### ISSUE TITLE
Walkthrough not updated in https://abce.readthedocs.io

### ISSUE THREAD

**Issue by DoofCoder** [AB-CE/abce#199]
Hi, I have seen that there were some needed changes in the walkthrough at the source files. However, those changes are not propagated to https://abce.readthedocs.io.

Are they supossed to? or is there another way to read the documentation?

**Comment by rht** [comment]
Thanks for reporting! I will dig into the issue, should be able to resolve in an hour or so.

**Comment by rht** [comment]
For some reason, the github webhook for readthedocs is gone, and this causes the docs to not be automatically updated. Only @DavoudTaghawiNejad has access to the readthedocs admin though, so it will take a little while.

**Comment by rht** [comment]
Fixed now!
