### ISSUE TITLE
Error when running abcEconomics using the latest flexx version (0.80)

### ISSUE THREAD

**Issue by rht** [AB-CE/abce#203]
```
Traceback (most recent call last):
  File "start.py", line 9, in <module>
    from abcEconomics import Simulation, gui
  File "/home/rht/code/venv/lib/python3.8/site-packages/abcEconomics/gui/__init__.py", line 8, in <module>
    from .basiclayout import basiclayout
  File "/home/rht/code/venv/lib/python3.8/site-packages/abcEconomics/gui/basiclayout.py", line 9, in <module>
    from .dockpanel import DockPanel
  File "/home/rht/code/venv/lib/python3.8/site-packages/abcEconomics/gui/dockpanel.py", line 1, in <module>
    from flexx.pyscript import window
ModuleNotFoundError: No module named 'flexx.pyscript'
```

The `flexx` API has changed.

**Comment by rht** [comment]
I reran this on latest version of flexx. No longer observed any errors.

**Comment by rht** [comment]
The unit tests worked, but some of the examples don't work with the gui. Reopening.

**Comment by mschlechtinger** [comment]
@rht thanks for the reply! I already tried manually downloading flexx 0.4.1 as well as cloning + changing the repo but I'm always encountering the same error  when I try to import the gui from abcEconomics.

this is the result of a pip freeze:
```
abcEconomics==0.9.7b2
alembic==1.4.2
banal==1.0.1
bkcharts==0.2
bokeh==0.12.16
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
Cython==0.29.21
dataset==0.8.0
dialite==0.5.2
flexx==0.4.1
future==0.18.2
idna==2.10
Jinja2==2.11.2
jsonpointer==2.0
Mako==1.1.3
MarkupSafe==1.1.1
normality==0.6.1
numpy==1.19.1
packaging==20.4
pandas==1.1.0
pscript==0.7.4
PyNSim==0.1.5
pyparsing==2.4.7
python-dateutil==2.8.1
python-editor==1.0.4
pytz==2020.1
PyYAML==5.3.1
requests==2.24.0
rfc3987==1.3.8
six==1.15.0
SQLAlchemy==1.3.18
strict-rfc3339==0.7
tornado==4.3
urllib3==1.25.10
validate-email==1.3
webruntime==0.5.7
```

**Comment by rht** [comment]
I found the error reported here: https://github.com/flexxui/flexx/issues/608. It is strange that the solution is to update to pscript 0.7.3, but you already have pscript 0.7.4. The other solution is to downgrade Python to 3.7, which is kind of annoying to do.

Maybe you shouldn't use `gui` for now.

**Comment by mschlechtinger** [comment]
@rht thanks a lot for the support! 
Downgrading does the trick for me atm. I hope flexx will fix this issue in the next couple of releases.

**Comment by rht** [comment]
#208 will remove the GUI code, so that `simulation.graphs()`, `@gui`, etc are now obsolete. If anyone wants to do GUI they can do it via the mature Jupyter widgets.

**Comment by rht** [comment]
https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Basics.html
