### ISSUE TITLE
abcEconomics.Trade is undefined.

### ISSUE THREAD

**Issue by arthurchen2018** [AB-CE/abce#206]
Hi,

I get another issue when I trying to do the example of one household and one firm.

(page 17-19) https://readthedocs.org/projects/abce/downloads/pdf/master/

The error message is:

AttributeError: module 'abcEconomics' has no attribute 'Trader', I think the Trader class is at:

\abcEconomics\agents\trader.py or do we have another way to call Trader?

Once I load the class Trader, then a new problem comes out: 

---> households.sell_labor()

abcEconomics.notenoughgoods.NotEnoughGoods: "('household', 0) 1 of good 'labor' missing"

Could you help me?

Thanks

-----------------------------------------------------------------------------------
households.sell_labor()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\AgentBasedBench\abcEconomics\group.py", line 59, in __call__
    self._scheduler.do(names, command, args, kwargs)
  File "D:\AgentBasedBench\abcEconomics\scheduler\singleprocess.py", line 52, in do
    ret = self.agents[name]._execute(command, args, kwargs)
  File "D:\AgentBasedBench\abcEconomics\agent.py", line 155, in _execute
    ret = getattr(self, command)(*args, **kwargs)
  File "<input>", line 17, in sell_labor
  File "D:\AgentBasedBench\abcEconomics\agents\trader.py", line 469, in sell
    raise NotEnoughGoods(self.name, good, quantity - available)
abcEconomics.notenoughgoods.NotEnoughGoods: "('household', 0) 1 of good 'labor' missing"
-----------------------------------------------------------------------------------------------------

**Comment by rht** [comment]
@arthurchen2018 thank you for the bug report. I have fixed the first error, i.e.
```
AttributeError: module 'abcEconomics' has no attribute 'Trader'
```
in https://github.com/AB-CE/abce/commit/d45fa88161476bba57d1242af0dbf99fc5424b3d. The `Agent` class already inherits from `Trader`, so there is no need for explicit inheritance.

I'm currently fixing the subsequent bugs.

**Comment by rht** [comment]
Fixed in master as of https://github.com/AB-CE/abce/commit/266c6d4e94bdb2e25e0d167747a1bdca139f9efa.
