### ISSUE TITLE
Mesa example not working

### ISSUE THREAD

**Issue by colbrydi** [AB-CE/abce#213]
We were trying to check out this project by running the mesa model example. Unfortunatly there is a bug in the code.  The model.py file is calling the following:

        abcEconomics.Simulation.__init__(self,
                                 name='abcEconomics and MESA integrated',
                                 rounds=300,
                                 processes=1)

but rounds is not a valid in the init function for the Simulation code.  

We also tried running the start.py example it is incomparable with the current version of mesa. Mesa is not part of the requirements.txt so we are not sure which ones to try.    

Let us know if you need more information to reproduce.  thank you.

**Comment by rht** [comment]
Did you use https://github.com/AB-CE/examples/tree/master/examples/mesa_example ? I tried running that example and it ran just fine.

I'm using the latest version of Mesa.

**Comment by rht** [comment]
I have updated the outdated Mesa example in this repo (https://github.com/AB-CE/abce/commit/d9f106104698dd1ccb91617f735b0d39b88b4f02). Thanks for the report! If this fixes your problem, you can close this issue.

**Comment by colbrydi** [comment]
This example is now working. Although it does require "pip install mesa" since mesa is not in the requirements.txt file but that is a fairly easy step.   thank you so much for such a quick turn around.
