### ISSUE TITLE
Installation error in python 3.11 with "numpy >= 1.10.2p"

### ISSUE THREAD

**Issue by andrewchch** [AB-CE/abce#218]
Hi All,

When trying:

pip install -e 'git+https://github.com/AB-CE/abce.git#egg=abcEconomics'

install on python 3.11 (earlier "pip install abcEconomics" failed with same error",  I get:

`  × python setup.py egg_info did not run successfully.
  │ exit code: 1                                      
  ╰─> [3 lines of output]
      error in abcEconomics setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          numpy >= 1.10.2p
                ~~~~~~~~~^
`

When I remove the trailing "p" from "1.10.2p", and run:

pip install -e .

in the src directory, the installation works. Any ideas?

Cheers,
Andrew

**Comment by rht** [comment]
I agree the "p" needs to be removed.

The upcoming release of Mesa 2.2.0 has an API has become similar to abcEconomics in expressivity, see https://github.com/projectmesa/mesa/pull/1916 and https://github.com/projectmesa/mesa/pull/1917. I am planning to gradually port the [examples](https://github.com/AB-CE/examples) to Mesa as well.

**Comment by andrewchch** [comment]
Thanks for the update, I'll close this issue.
