### ISSUE TITLE
Method name possession/possesions doesn't sound 'right'

### ISSUE THREAD

**Issue by rht** [AB-CE/abce#60]
Methods are meant to be verb. `agent17.get_good("neutrino")` reads better as a sentence than `agent17.possession("neutrino")`.

**Comment by DavoudTaghawiNejad** [comment]
resolved with the self['neutrino'] notation

**Comment by rht** [comment]
`self['neutrino']`, while it can be implemented in Python, is not cross-language if supposedly there will be multiple lang implementation of ABCE.

**Comment by DavoudTaghawiNejad** [comment]
I think get_good or get_goods should be implemented as well

**Comment by DavoudTaghawiNejad** [comment]
I replaced possessions with goods in panel_log and agg_log.
